# Generated by Django 5.0.3 on 2024-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='hof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourneyName', models.CharField(max_length=30)),
                ('teamName', models.CharField(max_length=30)),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('player3', models.CharField(max_length=30)),
                ('player4', models.CharField(max_length=30)),
                ('player5', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
