# Generated by Django 5.0.3 on 2024-05-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameid', models.BigAutoField(primary_key=True, serialize=False)),
                ('winner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInstance',
            fields=[
                ('instanceid', models.BigAutoField(primary_key=True, serialize=False)),
                ('playerlocation', models.IntegerField(max_length=1)),
                ('role', models.CharField(choices=[('t', 'TOP'), ('j', 'JUNGLE'), ('m', 'MID'), ('a', 'ADC'), ('s', 'SUP')], help_text='What role did they play', max_length=1)),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('ign', models.CharField(max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='statsviewer.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='statsviewer.player')),
            ],
        ),
    ]
