# Generated by Django 5.0.3 on 2024-05-04 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinstance',
            name='playerlocation',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)]),
        ),
    ]
