# Generated by Django 5.0.4 on 2024-05-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statsviewer', '0002_alter_playerinstance_playerlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('playerid', 'name')},
        ),
    ]
